CREATE TABLE [dbo].[htblzones] (
    [zoneid]     INT            IDENTITY (1, 1) NOT NULL,
    [name]       NVARCHAR (100) NOT NULL,
    [timezone]   NVARCHAR (100) NOT NULL,
    [country]    NVARCHAR (100) NOT NULL,
    [day1]       BIT            NOT NULL,
    [day2]       BIT            NOT NULL,
    [day3]       BIT            NOT NULL,
    [day4]       BIT            NOT NULL,
    [day5]       BIT            NOT NULL,
    [day6]       BIT            NOT NULL,
    [day7]       BIT            NOT NULL,
    [day1time1]  DATETIME       NOT NULL,
    [day1time2]  DATETIME       NOT NULL,
    [day2time1]  DATETIME       NOT NULL,
    [day2time2]  DATETIME       NOT NULL,
    [day3time1]  DATETIME       NOT NULL,
    [day3time2]  DATETIME       NOT NULL,
    [day4time1]  DATETIME       NOT NULL,
    [day4time2]  DATETIME       NOT NULL,
    [day5time1]  DATETIME       NOT NULL,
    [day5time2]  DATETIME       NOT NULL,
    [day6time1]  DATETIME       NOT NULL,
    [day6time2]  DATETIME       NOT NULL,
    [day7time1]  DATETIME       NOT NULL,
    [day7time2]  DATETIME       NOT NULL,
    [dateformat] NVARCHAR (20)  NOT NULL,
    [default]    BIT            NOT NULL,
    CONSTRAINT [PK_htblzones] PRIMARY KEY CLUSTERED ([zoneid] ASC) WITH (FILLFACTOR = 90)
);

