CREATE TABLE [dbo].[tblIEBHO] (
    [IEbhoID]     INT            IDENTITY (1, 1) NOT NULL,
    [AssetID]     INT            NOT NULL,
    [Control]     NVARCHAR (100) NULL,
    [Lastchanged] DATETIME       CONSTRAINT [DF_tblIEBHO_Lastchanged] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_tblIEBHO] PRIMARY KEY CLUSTERED ([IEbhoID] ASC) WITH (FILLFACTOR = 90, DATA_COMPRESSION = PAGE),
    CONSTRAINT [FK_tblIEBHO_tblAssets] FOREIGN KEY ([AssetID]) REFERENCES [dbo].[tblAssets] ([AssetID]) ON DELETE CASCADE NOT FOR REPLICATION
);


GO
CREATE NONCLUSTERED INDEX [IxFK_tblIEBHO_tblAssets]
    ON [dbo].[tblIEBHO]([AssetID] ASC) WITH (FILLFACTOR = 90, DATA_COMPRESSION = PAGE);

