CREATE TABLE [dbo].[htblsetup] (
    [defaultpriority]      INT            NULL,
    [editwarning]          INT            DEFAULT ((2)) NULL,
    [emailtickets]         BIT            DEFAULT ('1') NULL,
    [consoletickets]       BIT            DEFAULT ('1') NULL,
    [allowmerging]         BIT            DEFAULT ('1') NULL,
    [allowattachments]     BIT            DEFAULT ('1') NULL,
    [sortascending]        BIT            DEFAULT ('0') NULL,
    [selectunrelated]      BIT            DEFAULT ('1') NULL,
    [selectsamelocation]   BIT            DEFAULT ('0') NULL,
    [showschedule]         BIT            DEFAULT ('0') NULL,
    [showduedate]          BIT            DEFAULT ('0') NULL,
    [clientcc]             BIT            DEFAULT ('1') NULL,
    [showagentnotes]       BIT            DEFAULT ('0') NULL,
    [autoassign]           BIT            DEFAULT ('1') NULL,
    [assigntocreator]      BIT            DEFAULT ('0') NULL,
    [assigntype]           INT            DEFAULT ('1') NULL,
    [assignwhen]           INT            DEFAULT ('1') NULL,
    [assigntoeditor]       BIT            DEFAULT ('1') NULL,
    [standarddeadline]     BIGINT         DEFAULT ((1440)) NOT NULL,
    [maxkbarticles]        INT            DEFAULT ((5)) NOT NULL,
    [defaulttickettype]    INT            NULL,
    [pasteventsdeletion]   INT            DEFAULT ((180)) NOT NULL,
    [attachmentsfolder]    NVARCHAR (200) NULL,
    [usecustomfolder]      BIT            DEFAULT ((0)) NULL,
    [attfolderlogin]       NVARCHAR (100) NULL,
    [attfolderpass]        NVARCHAR (500) NULL,
    [clientsaddemail]      BIT            DEFAULT ((1)) NULL,
    [keepspamdays]         INT            DEFAULT ((-1)) NULL,
    [firstrun]             BIT            DEFAULT ((0)) NULL,
    [usedeadlines]         BIT            DEFAULT ((0)) NULL,
    [kbenabled]            BIT            DEFAULT ((1)) NULL,
    [kbagentonly]          BIT            DEFAULT ((0)) NULL,
    [defaultteamid]        INT            NULL,
    [shortcuts]            BIT            DEFAULT ((0)) NULL,
    [servernamechanged]    BIT            NULL,
    [showpriority]         BIT            DEFAULT ((0)) NULL,
    [ticketshover]         INT            DEFAULT ((0)) NULL,
    [allowselectotheruser] BIT            NULL,
    [clientclose]          BIT            DEFAULT ((1)) NULL,
    [attfolderkeyhash]     INT            NULL,
    [disablehelpdesk]      BIT            NULL,
    [showkbembeddedimages] BIT            CONSTRAINT [df_shokbwembeddedimages] DEFAULT ((1)) NULL,
    [kbattachmentstop]     BIT            CONSTRAINT [df_kbattachmentstop] DEFAULT ((1)) NULL
);

