CREATE TABLE [dbo].[htblemailaccounts] (
    [accountid]              INT             IDENTITY (1, 1) NOT NULL,
    [SMTPserver]             NVARCHAR (250)  NOT NULL,
    [incomingmailserver]     NVARCHAR (250)  NOT NULL,
    [address]                NVARCHAR (250)  NOT NULL,
    [displayname]            NVARCHAR (250)  NOT NULL,
    [sslincoming]            INT             DEFAULT ((0)) NULL,
    [ssloutgoing]            INT             DEFAULT ((0)) NULL,
    [authenticationincoming] BIT             DEFAULT ((0)) NULL,
    [authenticationoutgoing] BIT             DEFAULT ((0)) NULL,
    [usernameincoming]       NVARCHAR (50)   NULL,
    [usernameoutgoing]       NVARCHAR (50)   NULL,
    [passwordincoming]       NVARCHAR (1000) NULL,
    [passwordoutgoing]       NVARCHAR (1000) NULL,
    [SMTPport]               INT             NOT NULL,
    [serverport]             INT             NOT NULL,
    [default]                BIT             DEFAULT ('0') NULL,
    [protocol]               TINYINT         NOT NULL,
    [inboxfolders]           NVARCHAR (500)  DEFAULT ('') NOT NULL,
    [archivefolder]          NVARCHAR (500)  DEFAULT ('') NOT NULL,
    [trashfolder]            NVARCHAR (500)  DEFAULT ('') NOT NULL,
    [LastChanged]            DATETIME        DEFAULT (getdate()) NOT NULL,
    [errorincoming]          TINYINT         DEFAULT ((0)) NULL,
    [erroroutgoing]          TINYINT         DEFAULT ((0)) NULL,
    [lasttried]              DATETIME        DEFAULT (NULL) NULL,
    [aliases]                NTEXT           DEFAULT ('') NULL,
    [PasswordKeyHash]        INT             NULL,
    [noincoming]             BIT             DEFAULT ((0)) NOT NULL,
    [nooutgoing]             BIT             DEFAULT ((0)) NOT NULL,
    [protocoloutgoing]       TINYINT         DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_htblemailaccountss] PRIMARY KEY CLUSTERED ([accountid] ASC) WITH (FILLFACTOR = 90)
);

