CREATE TABLE [dbo].[tblGroupUni] (
    [GroupID] INT            IDENTITY (1, 1) NOT NULL,
    [Name]    NVARCHAR (300) NULL,
    [SID]     VARCHAR (300)  NULL,
    CONSTRAINT [PK_tblGroupUni] PRIMARY KEY CLUSTERED ([GroupID] ASC) WITH (FILLFACTOR = 90, DATA_COMPRESSION = PAGE),
    CONSTRAINT [IX_tblGroupUni] UNIQUE NONCLUSTERED ([Name] ASC, [SID] ASC) WITH (FILLFACTOR = 90, DATA_COMPRESSION = PAGE)
);

