CREATE TABLE [dbo].[TsysConfig] (
    [Config]                                 VARCHAR (50)    NOT NULL,
    [licensekey]                             VARCHAR (2000)  NULL,
    [datefrom]                               VARCHAR (8)     NULL,
    [dateto]                                 VARCHAR (8)     NULL,
    [Wolcommand]                             NVARCHAR (500)  CONSTRAINT [DF_TsysConfig_Wolcommand] DEFAULT (N'{actionpath}wol.exe {mac}') NULL,
    [Wolremovepoint]                         BIT             CONSTRAINT [DF_TsysConfig_Wolremovepoint] DEFAULT ((1)) NULL,
    [Actionpath]                             NVARCHAR (400)  NULL,
    [Trialdateto]                            VARCHAR (8)     NULL,
    [Schemaversion]                          INT             NULL,
    [Trialmode]                              BIT             NULL,
    [Firstrun]                               BIT             CONSTRAINT [DF_TsysConfig_Firstrun] DEFAULT ((1)) NOT NULL,
    [Reportrefresh]                          INT             CONSTRAINT [DF_TsysConfig_Reportrefresh] DEFAULT ((1)) NOT NULL,
    [AssetDashboard]                         BIT             CONSTRAINT [DF_TsysConfig_AssetDashboard] DEFAULT ((0)) NOT NULL,
    [UpdateCheck]                            BIT             CONSTRAINT [DF_TsysConfig_UpdateCheck] DEFAULT ((1)) NOT NULL,
    [LastUpdateCheck]                        DATETIME        CONSTRAINT [DF_TsysConfig_LastUpdateCheck] DEFAULT (getdate()-(15)) NOT NULL,
    [Qrcodehostname]                         NVARCHAR (300)  NULL,
    [MassEditInfo]                           BIT             DEFAULT ((1)) NOT NULL,
    [RenameWorkgroupCredential]              BIT             DEFAULT ((1)) NOT NULL,
    [Wolport]                                INT             DEFAULT ((7)) NOT NULL,
    [DefaultPackageShare]                    NVARCHAR (4000) NULL,
    [LatestLspushVersion]                    NVARCHAR (20)   NULL,
    [DefaultShareUsername]                   NVARCHAR (100)  NULL,
    [DefaultSharePassword]                   NVARCHAR (1000) NULL,
    [AssetState]                             NVARCHAR (200)  NULL,
    [DeploymentRunMode]                      INT             DEFAULT ((1)) NULL,
    [DoNotShrinkLogFiles]                    BIT             DEFAULT ((0)) NOT NULL,
    [ForceHttps]                             BIT             DEFAULT ((0)) NULL,
    [showbanner]                             BIT             DEFAULT ((0)) NULL,
    [banner]                                 NVARCHAR (100)  DEFAULT ('') NULL,
    [adminlogin]                             BIT             DEFAULT ((1)) NULL,
    [Agentstrialmode]                        INT             NULL,
    [Agentstrialdateto]                      NVARCHAR (8)    NULL,
    [WebsiteAccess]                          NVARCHAR (4000) NULL,
    [showrolechanges]                        BIT             DEFAULT ((0)) NOT NULL,
    [MultipleServersUseDefaultEncryptionKey] BIT             DEFAULT ((1)) NOT NULL,
    [DefaultShareKeyHash]                    INT             NULL,
    [DefaultLanguage]                        INT             DEFAULT ((1)) NOT NULL,
    [LanguageUpdate]                         INT             NULL,
    [ServerCurrentlyUpdating]                NVARCHAR (60)   NULL,
    [rebuildTicketIndex]                     BIT             NULL,
    [rebuildKBIndex]                         BIT             NULL,
    CONSTRAINT [PK_TblsysConfig] PRIMARY KEY CLUSTERED ([Config] ASC) WITH (FILLFACTOR = 90)
);

