CREATE TABLE [dbo].[rPrinterPageNorm]
(
	-- число отпечатко печатной техники
	[Id] INT NOT NULL PRIMARY KEY Identity (1,1),
	[AssetId] int not null, 
    [printedPages] INT NOT NULL default 0, 
    CONSTRAINT [FK_rPrinterPageNorm_tblAssets] FOREIGN KEY (AssetId) REFERENCES [tblAssets]([AssetId]) on delete Cascade, 
	[Yan] int not null default 0,
	[Feb] int not null default 0,
	[Mar] int not null default 0,
	[Apr] int not null default 0,
	[May] int not null default 0,
	[Jun] int not null default 0,
	[Jul] int not null default 0,
	[Aug] int not null default 0,
	[Sep] int not null default 0,
	[Okt] int not null default 0,
	[Nov] int not null default 0,
	[Dec] int not null default 0,
	[HOrg] nvarchar(255) null,
	[Filial] nvarchar(255) null,
	[Gorod] nvarchar(255) null,
	[Address] nvarchar(255) null,
	[Office] nvarchar(255) null,
	[Responce] nvarchar(255) null, 
    [YanF] INT NULL,
	[FebF] INT NULL,
	[MarF] INT NULL,
	[AprF] INT NULL,
	[MayF] INT NULL,
	[JunF] INT NULL,
	[JulF] INT NULL,
	[AugF] INT NULL,
	[SepF] INT NULL,
	[OktF] INT NULL,
	[NovF] INT NULL,
	[DecF] INT NULL,
	[Intence] int null
)
